apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version}}
  name: keycloak
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - {}
  ingress:
  - ports:
    - port: 7800
      protocol: TCP
    - port: 9000
      protocol: TCP
    - port: 8080
      protocol: TCP
  podSelector:
    matchLabels:
      app.kubernetes.io/component: keycloak
      app.kubernetes.io/instance: keycloak
      app.kubernetes.io/name: keycloak
  policyTypes:
  - Ingress
  - Egress
