apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version}}
  name: keycloak
  namespace: {{ .Release.Namespace }}
automountServiceAccountToken: false