{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: '9000'
    prometheus.io/scrape: 'true'
  labels:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: keycloak
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version}}
  name: keycloak-metrics
  namespace: keycloak
spec:
  ports:
  - name: metrics
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: https
    port: 8443
    protocol: TCP
    targetPort: 8443
  selector:
    app.kubernetes.io/component: keycloak
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: keycloak
  type: ClusterIP
{{- end }}